blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/nadomani/excalidraw-copilot/discussions
    about: Ask questions, share ideas, or show off your diagrams
